### ISSUE TITLE
Enhance for mobile

### ISSUE THREAD

**Issue by bsoyka** [mystery-egg/mystery-egg.github.io#1]
Right now, the site has the main content centered on the page, and it shows up very small on mobile devices, especially in portrait mode.  Since the page already includes Bootstrap, it should be fairly easy to optimize it for mobile devices.

If you'd like to help out with this issue, comment below and I will assign it to you.  Thank you in advance.

**Comment by pbrahmbhatt3** [comment]
can I work on it?

**Comment by bsoyka** [comment]
> can I work on it?

Sure, go ahead, @pbrahmbhatt3!  I’ll remove the `help wanted` label from this issue for you.

**Comment by pbrahmbhatt3** [comment]
Can you give me some more information about the bug. I tested it on my phone and it seems to be fine.

**Comment by bsoyka** [comment]
As shown below, the content appears small on devices with portrait mode.  I have also tested on a couple of phones with similar results.  I would like the content to be larger for such devices.

![4782384f-2b12-45c6-8ea8-1d54925da394](https://user-images.githubusercontent.com/37779854/53929907-3ef97380-4044-11e9-9a4d-363d8b77f364.jpeg)

**Comment by bsoyka** [comment]
@pbrahmbhatt3 Please respond or I will need to remove the `taken` label to let someone else try to help out.
