### ISSUE TITLE
Alphabetically sort the vars.js file

### ISSUE THREAD

**Issue by bsoyka** [mystery-egg/mystery-egg.github.io#14]
Just a quick bit of alphabetical sorting is needed so that it is easier to add or change the variables.

**Comment by bsoyka** [comment]
It is also perfectly fine to sort the lists in the variables as well.

**Comment by sowmiyamuthuraman** [comment]
can I work on this?

**Comment by bsoyka** [comment]
@sowmiyamuthuraman - Absolutely! Just fork the repository and make a pull request. Let me know if you have any questions, and thanks for volunteering to help out!
