### ISSUE TITLE
Create footer

### ISSUE THREAD

**Issue by bsoyka** [mystery-egg/mystery-egg.github.io#2]
The footer of this site should be fairly simple to make.

- [ ] [Logo](https://github.com/mystery-egg/mystery-egg.github.io/blob/master/logo.png) in bottom-left
- [ ] Link to GitHub repo in bottom-right
- [ ] Anchored to bottom
- [ ] Light gray background

If you'd like to help out with this issue, comment below and I will assign it to you. Thank you in advance.

**Comment by aqeelparpia** [comment]
Hello there i would love to help out with this issue. @bsoyka

**Comment by bsoyka** [comment]
> Hello there i would love to help out with this issue.

Alright, sounds good!  Let me know if you have any questions, @aqeelparpia.

**Comment by aqeelparpia** [comment]
successfully sent a pull request #3
