### ISSUE TITLE
Add cookie consent notification

### ISSUE THREAD

**Issue by bsoyka** [mystery-egg/mystery-egg.github.io#33]
To comply with GDPR laws, a cookie consent banner should be added.

This should be a notification that says something like:
```
By continuing to use this site, you consent to the use of cookies to store your preferences.
```

**Comment by FarhiaM** [comment]
Hi! Can i work on this issue?

**Comment by bsoyka** [comment]
@FarhiaM Go for it!

**Comment by FarhiaM** [comment]
Hi again @bsoyka , I forked your repo and when i opened index.html in a browser, I get a javascript error (without making changes to the code). Do you know how i can resolve this issue? :)

`helpers.ts:107 Uncaught TypeError: Cannot read property 'split' of null`

**Comment by bsoyka** [comment]
Hey, @FarhiaM! So sorry for the late response, this got *really* buried in my notifications.

I'm not sure how to fix that, but it shouldn't really affect the site.
